### ISSUE TITLE
Check if campaign token is provided in **Campaigns** `update` method

### ISSUE THREAD

**Issue by nicolasrouanne** [nomadeducation/batch-notifications-node#9]
### Description
The Campaigns `create` handler method doesn't check if the **notification token** is actually provided before making a `POST` request to the **Batch API**. This can result in unexpected behavior...
We might check if the token is actually provided.

```js
if (!token) {
            return Promise.reject(new Error(`Invalid or empty campaign token provided: $token`));
        }
```

### Reproduction
_Give as much details as possible to indicate how can we recreate this issue._
No reproduction needed. Code improvement issue.

Check this code segment in [`lib/Campaigns.js`](https://github.com/nomadeducation/batch-notifications-node/blob/master/lib/Campaign.js#L47):
```js
 static update (token, payload) {
        // don't send the payload if it's malformed
        const isValid = validate(payload);

        if (!isValid) {
            return Promise.reject(new Error(`payload invalid. Reason: "${ajv.errorsText(validate.errors)}"`));
        }

        return request.post(`/campaigns/update/${token}`, payload);
    }
```

**Comment by eilgin** [comment]
the token is now checked and validated in the code. Closing.
